# Generated by Django 6.0.6 on 2026-07-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_ativo_aluno_email_alter_aluno_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acessos', models.IntegerField()),
                ('acessos_restantes', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
        ),
    ]
