# Generated by Django 6.0.6 on 2026-07-20 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_pacoteacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.pacoteacesso')),
            ],
        ),
    ]
