# Generated by Django 6.0.6 on 2026-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_qrcodeacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeacesso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
