# Generated by Django 6.0.6 on 2026-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_qrcodeacesso_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeacesso',
            name='valido_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
